#!/bin/bash
#encoding: utf-8

# Import Settings
source $PWD/etc/skel
dir="$(dirname "$0")"

warning "Certifique-se de ter acesso sudo para que tudo funcione corretamente."
warning "Certifique-se se possui uma conexão com a Internet."

if [ "$#" -eq "0" ]; then
    # Opções padrões do sistema
    while true; do
        printf "\n  u: Atualizar\n"
        printf "  r: Remover aplicativos\n"
        printf "  i: Instalar aplicativos\n"
        printf "  c: Customizar\n"
        printf "  f: Executar processo completo\n"
        printf "  s: Reiniciar a máquina\n"
        printf "  h: Ver o manual de Usuário\n"
        printf "  q: Sair\n\n"
        read -p "Selecione uma opção: " opt
        process_option $opt
    done
else
    # Opções de linha de comando do sistema
    while [ "$1" != "" ]; do
        case $1 in
            -u | --upgrade )        . $dir/functions/upgrade.sh && upgrade
                                    #clear
                                    ;;
            -r | --remove )        . $dir/functions/cleanup.sh && cleanup
                                    #clear
                                    ;;
            -i | --install )           . $dir/functions/apps.sh && apps
                                    #clear
                                    ;;
            -c | --customize )    . $dir/functions/phanteon.sh && phanteon
                                    #clear
                                    ;;
            -f | --full )           . $dir/functions/upgrade.sh && upgrade
                                    . $dir/functions/apps.sh && apps
                                    . $dir/functions/phanteon.sh && phanteon
                                    . $dir/functions/cleanup.sh && cleanup
                                    #clear
                                    ;;
            -s | --shutdown )       shutdown -r now && exit
                                    ;;
            -h | --help )           man $PWD/man/manpage && exit
                                    ;;
            -q | --quit )           exit
                                    ;;
            * )                     warning "Opção inválida. Tente novamente." && exit 1
        esac
        shift
    done
fi
