#!/usr/bin/env bash

# Funções de mensagens
success() { printf "\33[32m  [✔] $1  \33[0m\n" ; }
error() { printf "\n\033[1;31m [X] $1  \33[0m\n" ; }
warning() { printf "\n\033[1;33m [!] $1  \33[0m\n"; }


check_resources() {
    # Checando conexão com a Internet
    wget -q --spider http://www.google.com
    if [ $? -eq 1 ]; then
        printf "\n\033[1;31m [X] Você está Offline. Conecte-se a Internet e tente novamente.\33[0m"
        printf "\n\033[1;31m [X] Alguns módulos do sistema não funcionam sem conexão com a Internet.\33[0m\n\n"
    fi

    # Checando Gerenciador de Pacotes
    [[ -d /var/cache/pacman/pkg/ ]] && PKGMAN='pacman'         
    [[ -d /var/cache/apt/archives ]] && PKGMAN='apt'

    if [[ $(which $PKGMAN 2>&1 /dev/null) ]]; then
        if [ $PKGMAN == "apt" ]; then
            . $PWD/lib/debian.sh
            APPS="$PWD/data/debian/apps.list"
            PURGED="$dir/data/debian/purge.list"
            DWLDS="$PWD/data/debian/downloads.list"
        else
            printf "\nDesculpe, mas seu gerenciador de pacotes ainda não é suportado.\n\n"
        fi
    else
        printf "\nSeu gerenciador de pacotes não pôde ser identificado.\n\n"
    fi
}


process_option() {
  case $1 in
    'u') # Atualizar o sistema
        . $PWD/functions/upgrade.sh && upgrade
        ;;
    'r') # Remover aplicativos
        . $PWD/functions/cleanup.sh && cleanup
        ;;
    'i') # Instalar aplicativos
        . $PWD/functions/apps.sh && apps
        ;;
    'c') # Customizar seu sistema
        . $PWD/functions/phanteon.sh && phanteon
        ;;
    'f') # Executar pós-instalação completa(todos os itens anteriores)
        . $PWD/functions/upgrade.sh && upgrade
        . $PWD/functions/apps.sh && apps
        . $PWD/functions/phanteon.sh && phanteon
        . $PWD/functions/cleanup.sh && cleanup
        break
        ;;
    's') # Desligar o sistema
        shutdown -r now
        break
        ;;
    'h') # Ver o manual do sistema
        man $PWD/man/manpage && exit
        ;;
    'q') # Sair do programa
        exit
        ;;
    *) # Opção inválida
        warning "Opção inválida. Tente novamente."
        ;;
  esac
}


# Exportando Funções
export success
export error
export warning
export check_resources
export -f process_option
